---
- name: install supercollider packages (debian)
  apt:
    state: present
    update_cache: yes
    install_recommends: no
    name: [ 'git',
            'jackd2',
            'supercollider',
            'sc3-plugins',
            'sc3-plugins-language',
            'sc3-plugins-server',
            'zlib1g-dev' ]

- name: install haskell packages (debian)
  apt:
    state: present
    update_cache: yes
    install_recommends: no
    name: [ 'cabal-install',
            'haskell-platform' ]
