---
- name: install haskell packages
  apt:
    state: present
    update_cache: no
    install_recommends: no
    name: [ 'cabal-install',
            'haskell-platform' ]

- name: install supercollider packages
  apt:
    state: present
    update_cache: no
    install_recommends: no
    name: [ 'supercollider',
            'sc3-plugins',
            'sc3-plugins-language',
            'sc3-plugins-server',
            'zlib1g-dev' ]
