---

- include: preinst_debian.yml
  when: ansible_distribution_file_variety == "Debian"

- include: install_debian.yml
  when: ansible_distribution_file_variety == "Debian"

- include: postinst.yml

