---

- name: make sure our user is in the audio group
  user: 
    name: "{{ansible_env.SUDO_USER}}"
    groups: audio
    append: yes
  register: adduser

- name: exit if sclang/supercollider is already running
  pids:
    name: sclang
  register: scpid
  failed_when: scpid.pids|length > 0

- block:
  - name: update cabal
    shell: cabal update  

  - name: compile and install tidal
    shell: cabal install tidal
    register: tidin
    changed_when: "not tidin.stdout is search('All the requested packages are already installed:')"

  - name: create template dest directory ~/.local/share (if required)
    file:
      path: "/home/{{ansible_env.SUDO_USER}}/.local/share"
      state: directory
      mode: '0775'

  - name: copy superdirt_*.scd templates to ~/.local/share/
    template:
      src: "templates/{{ item }}.scd.template"
      dest: "/home/{{ansible_env.SUDO_USER}}/.local/share/{{ item }}.scd"
      mode: 0640
    with_items:
      - superdirt_install
      - superdirt_check_install

  - name: set DISPLAY variable for sclang running
    set_fact:
      display: :99
    when: ansible_env.DISPLAY is not defined

  - set_fact:
      display: "{{ ansible_env.DISPLAY }}"
    when: display is not defined

  - name: check if SuperDirt is installed
    command: "sclang /home/{{ansible_env.SUDO_USER}}/.local/share/superdirt_check_install.scd"
    changed_when: false
    failed_when: false
    environment:
      DISPLAY: "{{ display }}"
    register: sdin

  - name: install/update SuperDirt (logging to: /tmp/sclang_tidal.log)
    shell: "sclang /home/{{ansible_env.SUDO_USER}}/.local/share/superdirt_install.scd 2>1 > /tmp/sclang_tidal.log"
    environment:
      DISPLAY: "{{ display }}"
    when: sdin.rc == 1

  - name: make sure our SuperCollider config dir exists
    file:
      path: "{{ sc_dir }}"
      state: directory
      mode: 0755

  - name: copy SuperCollider startup.scd template (backup any existing)
    template:
      src: templates/startup.scd.template
      dest: "{{ sc_dir }}/startup.scd"
      mode: 0640
      backup: yes

  become: yes
  become_method: su
  become_user: "{{ansible_env.SUDO_USER}}"
  become_flags: '-s /bin/bash'

- debug:
    msg: "NOTE: {{ansible_env.SUDO_USER}} has been added to audio group, logout/reboot **after** ansible finishes (waiting for 10s)"
  when: adduser.changed

- wait_for:
    timeout: 10
  when: adduser.changed

- block:
  - name: stop xvfb service
    systemd:
      state: stopped
      name: xvfb.tmp.service
  when: ansible_env.DISPLAY is not defined
