---

- name: make sure our user is in the audio group
  user: 
    name: "{{ansible_env.SUDO_USER}}"
    groups: audio
    append: yes
  register: adduser

- block:
  - name: update cabal
    shell: cabal update  

  - block:
    - name: workaround hosc version issue on older distros
      include_tasks: 01_hosc_fix.yml

    - name: reset supercollider config dir for older distros
      set_fact:
        sc_dir: "/home/{{ansible_env.SUDO_USER}}/.local/share/SuperCollider/"

    when: >
      (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 20) or
      (ansible_distribution == "Linux Mint" and ansible_distribution_major_version|int < 20)
  
  - name: compile and install tidal
    shell: cabal install tidal
    register: tidin
    changed_when: "not tidin.stdout is search('All the requested packages are already installed:')"

  - name: copy superdirt_init.scd template
    template:
      src: templates/superdirt_init.scd.template
      dest: /tmp/superdirt_init.scd
      mode: 0640

  - block:
    - name: install SuperDirt and samples in .local/share/SuperCollider/, via sclang shell
      shell: sh -c 'sclang /tmp/superdirt_init.scd | { sed "/SuperDirt installed/ q" && sleep 30; kill $$; }'
      failed_when: false
      register: sdin

    - name: check success of SuperDirt install
      fail:
        msg: "SuperDirt install failed: {{ sdin.stdout }}"
      failed_when: "not sdin.stdout is search('SuperDirt installed')"

    when: ansible_env.DISPLAY is defined

  - block:
    - name: install SuperDirt and samples in .local/share/SuperCollider/, via sclang shell (HEADLESS option)
      shell: sh -c 'sclang /tmp/superdirt_init.scd | { sed "/SuperDirt installed/ q" && sleep 30; kill $$; }'
      failed_when: false
      register: hsdin
      environment:
        DISPLAY: :99

    - name: check success of SuperDirt install
      fail:
        msg: "SuperDirt install failed: {{ hsdin.stdout }}"
      failed_when: "not hsdin.stdout is search('SuperDirt installed')"
    when: ansible_env.DISPLAY is not defined

  - name: copy SuperCollider startup.scd template (backup any existing)
    template:
      src: templates/startup.scd.template
      dest: "{{ sc_dir }}/startup.scd"
      mode: 0640
      backup: yes

  become: yes
  become_method: su
  become_user: "{{ansible_env.SUDO_USER}}"
  become_flags: '-s /bin/bash'

- debug:
    msg: "NOTE: {{ansible_env.SUDO_USER}} has been added to audio group, logout/reboot **after** ansible finishes (waiting for 10s)"
  when: adduser.changed

- wait_for:
    timeout: 10
  when: adduser.changed

- name: get pid of dangling sclang process we may have left behind
  shell: ps aux | grep sclang | grep -m 1 superdirt_init.scd | awk '{print $2}'
  register: scpid
  changed_when: false

- name: kill dangling sclang process if required
  shell: "kill {{ scpid.stdout }}"
  when: scpid.stdout != ""
  failed_when: false

- block:
  - name: stop xvfb service
    systemd:
      state: stopped
      name: xvfb.tmp.service
  when: ansible_env.DISPLAY is not defined
