---
- block:
  - name: install xvfb (Archlinux)
    pacman:
      state: latest
      update_cache: yes
      name: xorg-server-xvfb

  - name: install xvfb service file temporarily (Archlinux)
    template:
      src: templates/xvfb.tmp.service.template
      dest: /etc/systemd/system/xvfb.tmp.service
      owner: root
      group: root

  - name: start xvfb service (Archlinux)
    systemd:
      state: started
      name: xvfb.tmp.service
  when: ansible_env.DISPLAY is not defined

- name: install ansible task dependencies (Archlinux)
  pacman:
    state: present
    update_cache: yes
    name: [ 'coreutils' ]

